# -*- coding: utf-8 -*-
"""try_catch

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RKxkHSWf5bfiZHsz2PhFkSzN7BoE9jeH
"""

filename = 'name.txt'

try:
    with open(filename, 'r') as file:
        contents = file.read()
        print(contents)

except FileNotFoundError:
    print(f"No such file or directory: '{filename}' The file has been closed.")

except IsADirectoryError:
    print(f"The path '{filename}' is a directory, not a file.")

except Exception as e:
    print(f"An unexpected error occurred: {e}")